FROM devopsdockeruh/simple-web-service:alpine
# Since the base image already have an `ENTRYPOINT` command, the `CMD` command defined here will work as a way to pass arguments to the `ENTRYPOINT` command. With that in mind, we'll pass a 'server' argument
CMD server