version: '3.8'

services:
    simple-web-service:
      # Set the image
      image: devopsdockeruh/simple-web-service
      # The container listen the port 8080
      ports:
        - 8080:8080
      # The command 'server' starts the service, so that we can access it via http://localhost:8080
      command: server